### ISSUE TITLE
what is the tensorflow version should be?

### ISSUE THREAD

**Issue by SeekPoint** [muhaochen/on2vec#1]
mldl@ub1604:~/ub16_prj/on2vec/yago_wohm$ PYTHONPATH=../src python training_yago.py 
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Loaded ../on2vec-yg60k/Yago/yagoFactsFilt15kTest.tsv to triples_record.
Traceback (most recent call last):
  File "training_yago.py", line 53, in <module>
    m_train.build(this_data, dim=100, batch_size=500, save_path = model_path, data_save_path = data_path, L1=False)
  File "/home/mldl/ub16_prj/on2vec/src/trainer.py", line 36, in build
    L1=self.L1)
  File "/home/mldl/ub16_prj/on2vec/src/model.py", line 44, in __init__
    self.build()
  File "/home/mldl/ub16_prj/on2vec/src/model.py", line 146, in build
    A_loss_matrix = tf.sub(
AttributeError: 'module' object has no attribute 'sub'
mldl@ub1604:~/ub16_prj/on2vec/yago_wohm$

**Comment by muhaochen** [comment]
Changed tf.sub to tf.subtract
The original version was pre-1.0.

**Comment by SeekPoint** [comment]
I use tf1.0.1 and had sub changed to subtract:

mldl@ub1604:~/ub16_prj/on2vec/yago_wohm$ PYTHONPATH=../src python training_yago.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Loaded ../on2vec-yg60k/Yago/yagoFactsFilt15kTest.tsv to triples_record.
Traceback (most recent call last):
  File "training_yago.py", line 53, in <module>
    m_train.build(this_data, dim=100, batch_size=500, save_path = model_path, data_save_path = data_path, L1=False)
  File "/home/mldl/ub16_prj/on2vec/src/trainer.py", line 36, in build
    L1=self.L1)
  File "/home/mldl/ub16_prj/on2vec/src/model.py", line 44, in __init__
    self.build()
  File "/home/mldl/ub16_prj/on2vec/src/model.py", line 176, in build
    tf.maximum(tf.subtract(tf.sqrt(tf.reduce_sum(tf.square(A_hn_con_batch), 1)), 1.), 0.), tf.maximum(tf.subtract(tf.sqrt(tf.reduce_sum(tf.square(A_tn_con_batch), 1)), 1.), 0.)])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 637, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 702, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 110, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 99, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
mldl@ub1604:~/ub16_prj/on2vec/yago_wohm$ 
mldl@ub1604:~/ub16_prj/on2vec/yago_wohm$

**Comment by muhaochen** [comment]
Fixed tf.concat;  tf has switched the arguments axis and values since 1.0 (sorry the code was written long time ago).

**Comment by SeekPoint** [comment]
it works
